apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rh-service-binding-operator
  labels:
    operators.coreos.com/rh-service-binding-operator.openshift-operators: ''
    {{- include "service-binding-operator.labels" . | nindent 4 }}
spec:
  channel: stable
  installPlanApproval: Automatic
  name: rh-service-binding-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
